results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD/MERGEETL60_rcp85
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: rcp85
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
