module: /home/liruixue/repos_release//energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim_lininter_double/break2_Exclude/semi-parametric/Projection_Configs/model/hddcddspline_OTHERIND_electricity.yml
mode: median
outputdir: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD
do_farmers: true
do_historical: true
deltamethod: no
only-ssp: SSP3
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
yearcovarscale: 2
