module: /global/scratch/liruixue/repos/energy-code-release-2020/pixel_interaction/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/laika/model/hddcddspline_OTHERIND_other_energy.yml
mode: median
outputdir: /global/scratch/liruixue/outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD
do_farmers: true
do_historical: true
deltamethod: no
only-ssp: SSP3
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 7.713
