outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
levels-weighting: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
levels-unit: GJ
aggregated-unit: GJ
aggregate-weighting-numerator: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: MERGEETL60_rcp45pc
rcp: rcp45
only-farmers: ['', 'histclim']
