outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD_dm
levels-weighting: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
levels-unit: dollar
aggregated-unit: dollar
aggregate-weighting-numerator: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: sum-to-1
infix: MERGEETL60_rcp45
rcp: rcp45
only-farmers: ['', 'histclim']
