outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD_dm
levels-weighting: population * social/baselines/energy/REMINDMAgPIE1730_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
levels-unit: GJ
aggregated-unit: GJ
aggregate-weighting-numerator: population * social/baselines/energy/REMINDMAgPIE1730_rcp45_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: population
infix: REMINDMAgPIE1730_rcp45pc
rcp: rcp45
only-farmers: ['', 'histclim']
