results-root: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
output-dir: /shares/gcp/social/parameters/energy_pixel_interaction/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_GMFD/median_OTHERIND_electricity_TINV_clim_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
