results-root: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_GMFD/median_OTHERIND_other_energy_TINV_clim_GMFD/WITCHGLOBIOM42_rcp45
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: rcp45
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
