results-root: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD
deltamethod: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD_dm
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_double_GMFD/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', .5, 0.05, 0.17, 0.83, 0.95, 0.10, 0.90, 0.75, 0.25]
output-format: edfcsv
