outputdir: outputs/energy/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_income_spline_GMFD_dm
levels-weighting: population * social/baselines/energy/WITCHGLOBIOM42_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/WITCHGLOBIOM42_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: WITCHGLOBIOM42_rcp45pc
rcp: rcp45
