outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0_GLOBAL_COMPILE.dta:country:year:other_energycompile_price
targetdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_dm/rcp85/CCSM4/high/SSP3
levels-unit: dollar
aggregated-unit: dollar
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0_GLOBAL_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: sum-to-1
infix: price0
