import: /home/liruixue/repos/energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/sacagawea/model/hddcddspline_OTHERIND_electricity.yml
mode: median
outputdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost
singledir: single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_rff_test
do_farmers: true
iam: rff
ssp: 6546
only-models: ["CCSM4"]
do_historical: true
deltamethod: no
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
