module: /home/liruixue/repos/energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/sacagawea/model/hddcddspline_OTHERIND_electricity.yml
mode: writecalcs
outputdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost
singledir: single-OTHERIND_electricity_FD_FGLS_1401_TINV_clim_GMFD_slow_adapt
do_farmers: true
do_historical: true
deltamethod: no
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 9.087
slowadapt: both
rcp: rcp45