outputdir: outputs/energy_pixel_interaction/impacts-blueghost
levels-weighting: population * social/baselines/energy:country:year:other_energycompile_
targetdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_dm/rcp85/CCSM4/high/SSP3
aggregate-weighting-numerator: population * social/baselines/energy:country:year:other_energycompile_
aggregate-weighting-denominator: population
infix: integrationpc
