outputdir: outputs/energy_pixel_interaction/impacts-blueghost
weighting: population
targetdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_dm/rcp85/CCSM4/high/SSP3
only-farmers: ['', 'histclim']
ssp: SSP3