outputdir: outputs/energy_pixel_interaction/impacts-blueghost
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_pricem
targetdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD/rcp85/CCSM4/high/SSP3
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_pricem
aggregate-weighting-denominator: sum-to-1
infix: pricem0027
