outputdir: outputs/energy/impacts-blueghost
weighting: population
targetdir: /shares/gcp/outputs/energy/impacts-blueghost/single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_income_spline_lininter_double_GMFD/rcp85/CCSM4/high/SSP3
