outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_GMFD_dm
weighting: population
levels-unit: GJ
aggregated-unit: GJ
only-farmers: ['', 'histclim']
