outputdir: outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0_GLOBAL_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_gr0_GLOBAL_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: population
infix: price0pc
