results-root:
  FD_FGLS_inter_OTHERIND_other_energy_TINV_clim.*: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD
  FD_FGLS_inter_OTHERIND_electricity_TINV_clim.*: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_GMFD/total_energy
file-organize: [ssp, rcp]
do-montecarlo: no
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
