outputdir: outputs/energy/impacts-blueghost
levels-weighting: population * social/baselines/energy/REMINDMAgPIE1730_rcp85_Prices_COMPILE.dta:country:year:other_energycompile_price
targetdir: /shares/gcp/outputs/energy/impacts-blueghost/single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_income_spline_GMFD_dm/rcp85/CCSM4/high/SSP3
aggregate-weighting-numerator: population * social/baselines/energy/REMINDMAgPIE1730_rcp85_Prices_COMPILE.dta:country:year:other_energycompile_price
aggregate-weighting-denominator: population
infix: REMINDMAgPIE1730_rcp85pc
rcp: rcp85
