results-root: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_lininter_GMFD
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_GMFD/median_OTHERIND_other_energy_TINV_clim_lininter_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
