module: /home/liruixue/repos_release//energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/model/hddcddspline_OTHERIND_other_energy.yml
mode: median
outputdir: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD
do_farmers: true
do_historical: true
deltamethod: no
only-ssp: [SSP1,SSP2,SSP3,SSP4,SSP5]
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 7.713
