results-root: /shares/gcp/outputs/energy/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_income_spline_GMFD/median_OTHERIND_other_energy_TINV_clim_income_spline_GMFD
file-organize: [ssp, rcp]
do-montecarlo: no
only-rcp: rcp85
only-models: all
only-iam: null
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
