outputdir: outputs/energy_pixel_interaction/impacts-blueghost
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_grm0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_price
targetdir: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/median/rcp45/CCSM4/rff/6546
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_grm0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: sum-to-1
infix: pricem0027
