outputdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost
weighting: population
targetdir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/single-OTHERIND_electricity_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_lininter_GMFD/rcp85/CCSM4/high/SSP3
levels-unit: GJ
aggregated-unit: GJ
only-farmers: ['', 'histclim']
