results-root: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/projection_system_outputs/raw_projection_output/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_lininter_half_GMFD
output-dir: /Users/ruixueli/Downloads/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_half_GMFD/median_OTHERIND_other_energy_TINV_clim_lininter_half_GMFD/price014pc
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
