results-root: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_GMFD/median_OTHERIND_other_energy_TINV_clim_GMFD/REMINDMAgPIE1730_rcp45pc
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: rcp45
only-models: all
only-iam: null
column: rebased
output-format: valuescsv
