module: /global/scratch/liruixue/repos/energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/laika/model/hddcddspline_OTHERIND_other_energy.yml
mode: writecalcs
outputdir: /global/scratch/liruixue/outputs/energy_pixel_interaction/impacts-blueghost
singledir: single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD
do_farmers: true
do_historical: true
deltamethod: no
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 7.713
