results-root: impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD_dm
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_lininter_double_GMFD/median_OTHERIND_electricity_TINV_clim_lininter_double_GMFD/impactpc
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
deltamethod: true
column: rebased
output-format: valuescsv
