outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD
levels-weighting: population * social/baselines/energy/REMINDMAgPIE1730_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/REMINDMAgPIE1730_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: sum-to-1
infix: REMINDMAgPIE1730_rcp45
rcp: rcp45
only-farmers: ['', 'histclim']
