outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD_dm
levels-weighting: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-numerator: population * social/baselines/energy/MERGEETL60_rcp45_Prices_COMPILE.dta:country:year:electricitycompile_price
aggregate-weighting-denominator: population
infix: MERGEETL60_rcp45pc
rcp: rcp45
ssp: SSP3