outputdir: outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_GMFD_dm
levels-weighting: population * social/baselines/energy/IEA_Price_FIN_Clean_grm0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_pricem
aggregate-weighting-numerator: population * social/baselines/energy/IEA_Price_FIN_Clean_grm0027_GLOBAL_COMPILE.dta:country:year:electricitycompile_pricem
aggregate-weighting-denominator: sum-to-1
infix: pricem0027
only-farmers: ['', 'histclim']
