results-root: impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_GMFD_dm
output-dir: /home/liruixue/energy_data_release/OUTPUT/extracted_projection_data/TINV_clim_GMFD/median_OTHERIND_other_energy_TINV_clim_GMFD/pricem0027
file-organize: [ssp, region]
do-montecarlo: no
only-rcp: null
only-models: all
only-iam: null
deltamethod: true
column: rebased
output-format: valuescsv
