results-root:
  FD_FGLS_inter_OTHERIND_other_energy_TINV_clim_lininter_double.*: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_other_energy_TINV_clim_lininter_double__lin_dm
  FD_FGLS_inter_OTHERIND_electricity_TINV_clim_lininter_double.*: /shares/gcp/outputs/energy_pixel_interaction/impacts-blueghost/median_OTHERIND_electricity_TINV_clim_lininter_double__lin_dm
multiimpact_vcv: /home/liruixue/repos/energy-code-release-2020/pixel_interaction/projection_inputs/csvv/TINV_clim_lininter_double/FD_FGLS_inter_OTHERIND_TINV_clim_lininter_double-fixed.csv
output-dir: /shares/gcp/social/parameters/energy/extraction/multi-models/rationalized_code/break2_Exclude_all-issues_semi-parametric/TINV_clim_lininter_double_GMFD/total_energy
file-organize: [ssp, rcp]
do-montecarlo: no
only-models: all
only-iam: null
deltamethod: true
column: rebased
evalqvals: ['mean', 0.05, 0.95]
output-format: edfcsv
