module: /home/liruixue/repos_release//energy-code-release-2020/projection_inputs/configs/GMFD/TINV_clim/break2_Exclude/semi-parametric/Projection_Configs/model/hddcddspline_OTHERIND_other_energy.yml
mode: writecalcs
outputdir: impacts-blueghost
singledir: single-OTHERIND_other_energy_FD_FGLS_719_Exclude_all-issues_break2_semi-parametric_TINV_clim_GMFD_dm
do_farmers: true
do_historical: true
deltamethod: yes
econcovar:
   class: mean
   length: 15
climcovar:
   class: mean
   length: 15
loggdppc-delta: 7.713
timeout: 30
